
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='antsibull',
    version='0.20.0',
    description='Tools for building the Ansible Distribution',
    python_requires='==3.*,>=3.6.0',
    project_urls={"repository": "https://github.com/ansible-community/antsibull"},
    author='Toshio Kuratomi',
    author_email='a.badger@gmail.com',
    license='GPL-3.0-or-later',
    entry_points={"console_scripts": ["antsibull-build = antsibull.cli.antsibull_build:main", "antsibull-lint = antsibull.cli.antsibull_lint:main", "antsibull-docs = antsibull.cli.antsibull_docs:main"]},
    packages=['antsibull', 'antsibull.cli', 'antsibull.cli.doc_commands', 'antsibull.data', 'antsibull.data.docsite', 'antsibull.docs_parsing', 'antsibull.jinja2', 'antsibull.schemas', 'antsibull.utils', 'antsibull.vendored'],
    package_dir={"": "."},
    package_data={"antsibull.data": ["*.j2", "*.rst", "*.txt", "debian/*.j2"], "antsibull.data.docsite": ["*.j2"]},
    install_requires=['aiocontextvars; python_version == "3.6.*" and python_version >= "3.6.0"', 'aiofiles', 'aiohttp', 'antsibull-changelog>=0.7.0', 'asyncio-pool', 'docutils', 'jinja2', 'packaging>=20.0', 'perky', 'pydantic', 'pyyaml', 'rstcheck==3.*,>=3.0.0', 'semantic-version', 'sh', 'twiggy>=0.5.0'],
    extras_require={"dev": ["asynctest==0.*,>=0.13.0", "codecov==2.*,>=2.0.22", "cryptography==2.*,>=2.9.2", "flake8>=3.8.0", "mypy==0.*,>=0.770.0", "pylint==2.*,>=2.5.2", "pyre-check==0.*,>=0.0.46", "pytest==5.*,>=5.4.1", "pytest-asyncio>=0.12", "pytest-cov==2.*,>=2.8.1"]},
)
